package com.intuit.jsonoutput

import org.apache.spark.sql.SparkSession

object CsvToJson {
  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder.master("local[10]").appName("Read CSV File")
      .config("spark.some.config.option", "some-value")
      .getOrCreate()

    import spark.implicits._
    val csvDF = spark.read.option("header", "true")
      .option("delimiter", "|")
      .option("inferSchema", "true")
      //.csv("/Users/pswain1/workspace/JsonFormatOutput/src/main/resources/test.csv")
      .csv("/Users/pswain1/workspace/JsonFormatOutput/src/main/resources/INTUIT_USA_ACTIVE_SEP2018_newheaders.csv")
      //.json("/Users/pswain1/workspace/JsonFormatOutput/src/main/resources/abc.json")


    //csvDF.count()

    var newDF = csvDF
    for (col <- csvDF.columns) {
      newDF = newDF.withColumnRenamed(col, col.replaceAll("\\s", "_"))
    }

     //newDF.show()
    //newDF.cache()



        val BUSINESS_NAME = newDF.filter($"BUSINESS_NAME".contains("Shopify") || $"BUSINESS_NAME".contains("Square") || $"BUSINESS_NAME".contains("BigCommerce") || $"BUSINESS_NAME".contains("Wix") || $"BUSINESS_NAME".contains("SquareSpace") || $"BUSINESS_NAME".contains("Weebly") || $"BUSINESS_NAME".contains("WooCommerce") || $"BUSINESS_NAME".contains("Creditkarma") || $"BUSINESS_NAME".contains("CreditSesame") || $"BUSINESS_NAME".contains("Bankrate") || $"BUSINESS_NAME".contains("Nerdwallet") || $"BUSINESS_NAME".contains("Clearscore") || $"BUSINESS_NAME".contains("Noddle") || $"BUSINESS_NAME".contains("LendingTree") || $"BUSINESS_NAME".contains("Fathom") || $"BUSINESS_NAME".contains("Qvinci") || $"BUSINESS_NAME".contains("Spotlight") || $"BUSINESS_NAME".contains("Liveplan") || $"BUSINESS_NAME".contains("Float") || $"BUSINESS_NAME".contains("Futrli") || $"BUSINESS_NAME".contains("Wagepoint") || $"BUSINESS_NAME".contains("Payment Evolution") || $"BUSINESS_NAME".contains("Xero") || $"BUSINESS_NAME".contains("KeyPay") || $"BUSINESS_NAME".contains("Robinhood") || $"BUSINESS_NAME".contains("Acorns") || $"BUSINESS_NAME".contains("Digit") || $"BUSINESS_NAME".contains("Wealthfront") || $"BUSINESS_NAME".contains("MoneyLion") || $"BUSINESS_NAME".contains("Betterment"))
    BUSINESS_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/TESTRESULT6")



/*
    val BUSINESS_NAME = csvDF.filter($"BUSINESS_NAME".contains("Shopify"))

    //val BUSINESS_NAME = newDF.filter($"BUSINESS_NAME".contains("Shopify") || $"BUSINESS_NAME".contains("Square"))
    BUSINESS_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/TESTRESULT4")

*/
        /*
        val STREET_ADDRESS = newDF.filter($"STREET_ADDRESS".contains("Shopify") || $"STREET_ADDRESS".contains("Square") || $"STREET_ADDRESS".contains("BigCommerce") || $"STREET_ADDRESS".contains("Wix") || $"STREET_ADDRESS".contains("SquareSpace") || $"STREET_ADDRESS".contains("Weebly") || $"STREET_ADDRESS".contains("WooCommerce") || $"STREET_ADDRESS".contains("Creditkarma") || $"STREET_ADDRESS".contains("CreditSesame") || $"STREET_ADDRESS".contains("Bankrate") || $"STREET_ADDRESS".contains("Nerdwallet") || $"STREET_ADDRESS".contains("Clearscore") || $"STREET_ADDRESS".contains("Noddle") || $"STREET_ADDRESS".contains("LendingTree") || $"STREET_ADDRESS".contains("Fathom") || $"STREET_ADDRESS".contains("Qvinci") || $"STREET_ADDRESS".contains("Spotlight") || $"STREET_ADDRESS".contains("Liveplan") || $"STREET_ADDRESS".contains("Float") || $"STREET_ADDRESS".contains("Futrli") || $"STREET_ADDRESS".contains("Wagepoint") || $"STREET_ADDRESS".contains("Payment Evolution") || $"STREET_ADDRESS".contains("Xero") || $"STREET_ADDRESS".contains("KeyPay") || $"STREET_ADDRESS".contains("Robinhood") || $"STREET_ADDRESS".contains("Acorns") || $"STREET_ADDRESS".contains("Digit") || $"STREET_ADDRESS".contains("Wealthfront") || $"STREET_ADDRESS".contains("MoneyLion") || $"STREET_ADDRESS".contains("Betterment"))
        //val STREET_ADDRESS2 = newDF.filter($"STREET_ADDRESS2".contains("Shopify") || $"STREET_ADDRESS2".contains("Square") || $"STREET_ADDRESS2".contains("BigCommerce") || $"STREET_ADDRESS2".contains("Wix") || $"STREET_ADDRESS2".contains("SquareSpace") || $"STREET_ADDRESS2".contains("Weebly") || $"STREET_ADDRESS2".contains("WooCommerce") || $"STREET_ADDRESS2".contains("Creditkarma") || $"STREET_ADDRESS2".contains("CreditSesame") || $"STREET_ADDRESS2".contains("Bankrate") || $"STREET_ADDRESS2".contains("Nerdwallet") || $"STREET_ADDRESS2".contains("Clearscore") || $"STREET_ADDRESS2".contains("Noddle") || $"STREET_ADDRESS2".contains("LendingTree") || $"STREET_ADDRESS2".contains("Fathom") || $"STREET_ADDRESS2".contains("Qvinci") || $"STREET_ADDRESS2".contains("Spotlight") || $"STREET_ADDRESS2".contains("Liveplan") || $"STREET_ADDRESS2".contains("Float") || $"STREET_ADDRESS2".contains("Futrli") || $"STREET_ADDRESS2".contains("Wagepoint") || $"STREET_ADDRESS2".contains("Payment Evolution") || $"STREET_ADDRESS2".contains("Xero") || $"STREET_ADDRESS2".contains("KeyPay") || $"STREET_ADDRESS2".contains("Robinhood") || $"STREET_ADDRESS2".contains("Acorns") || $"STREET_ADDRESS2".contains("Digit") || $"STREET_ADDRESS2".contains("Wealthfront") || $"STREET_ADDRESS2".contains("MoneyLion") || $"STREET_ADDRESS2".contains("Betterment"))
        val CITY_NAME = newDF.filter($"CITY_NAME".contains("Shopify") || $"CITY_NAME".contains("Square") || $"CITY_NAME".contains("BigCommerce") || $"CITY_NAME".contains("Wix") || $"CITY_NAME".contains("SquareSpace") || $"CITY_NAME".contains("Weebly") || $"CITY_NAME".contains("WooCommerce") || $"CITY_NAME".contains("Creditkarma") || $"CITY_NAME".contains("CreditSesame") || $"CITY_NAME".contains("Bankrate") || $"CITY_NAME".contains("Nerdwallet") || $"CITY_NAME".contains("Clearscore") || $"CITY_NAME".contains("Noddle") || $"CITY_NAME".contains("LendingTree") || $"CITY_NAME".contains("Fathom") || $"CITY_NAME".contains("Qvinci") || $"CITY_NAME".contains("Spotlight") || $"CITY_NAME".contains("Liveplan") || $"CITY_NAME".contains("Float") || $"CITY_NAME".contains("Futrli") || $"CITY_NAME".contains("Wagepoint") || $"CITY_NAME".contains("Payment Evolution") || $"CITY_NAME".contains("Xero") || $"CITY_NAME".contains("KeyPay") || $"CITY_NAME".contains("Robinhood") || $"CITY_NAME".contains("Acorns") || $"CITY_NAME".contains("Digit") || $"CITY_NAME".contains("Wealthfront") || $"CITY_NAME".contains("MoneyLion") || $"CITY_NAME".contains("Betterment"))
        val GLOBAL_ULTIMATE_BUSINESS_NAME = newDF.filter($"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Shopify") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Square") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("BigCommerce") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Wix") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("SquareSpace") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Weebly") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("WooCommerce") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Creditkarma") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("CreditSesame") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Bankrate") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Nerdwallet") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Clearscore") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Noddle") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("LendingTree") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Fathom") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Qvinci") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Spotlight") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Liveplan") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Float") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Futrli") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Wagepoint") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Payment Evolution") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Xero") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("KeyPay") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Robinhood") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Acorns") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Digit") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Wealthfront") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("MoneyLion") || $"GLOBAL_ULTIMATE_BUSINESS_NAME".contains("Betterment"))
        val HEADQUARTER_PARENT_BUSINESS_NAME = newDF.filter($"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Shopify") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Square") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("BigCommerce") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Wix") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("SquareSpace") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Weebly") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("WooCommerce") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Creditkarma") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("CreditSesame") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Bankrate") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Nerdwallet") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Clearscore") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Noddle") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("LendingTree") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Fathom") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Qvinci") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Spotlight") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Liveplan") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Float") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Futrli") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Wagepoint") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Payment Evolution") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Xero") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("KeyPay") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Robinhood") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Acorns") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Digit") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Wealthfront") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("MoneyLion") || $"HEADQUARTER/PARENT_BUSINESS_NAME".contains("Betterment"))
        val CEO_NAME = newDF.filter($"CEO_NAME".contains("Shopify") || $"CEO_NAME".contains("Square") || $"CEO_NAME".contains("BigCommerce") || $"CEO_NAME".contains("Wix") || $"CEO_NAME".contains("SquareSpace") || $"CEO_NAME".contains("Weebly") || $"CEO_NAME".contains("WooCommerce") || $"CEO_NAME".contains("Creditkarma") || $"CEO_NAME".contains("CreditSesame") || $"CEO_NAME".contains("Bankrate") || $"CEO_NAME".contains("Nerdwallet") || $"CEO_NAME".contains("Clearscore") || $"CEO_NAME".contains("Noddle") || $"CEO_NAME".contains("LendingTree") || $"CEO_NAME".contains("Fathom") || $"CEO_NAME".contains("Qvinci") || $"CEO_NAME".contains("Spotlight") || $"CEO_NAME".contains("Liveplan") || $"CEO_NAME".contains("Float") || $"CEO_NAME".contains("Futrli") || $"CEO_NAME".contains("Wagepoint") || $"CEO_NAME".contains("Payment Evolution") || $"CEO_NAME".contains("Xero") || $"CEO_NAME".contains("KeyPay") || $"CEO_NAME".contains("Robinhood") || $"CEO_NAME".contains("Acorns") || $"CEO_NAME".contains("Digit") || $"CEO_NAME".contains("Wealthfront") || $"CEO_NAME".contains("MoneyLion") || $"CEO_NAME".contains("Betterment"))
        val CEO_FIRST_NAME = newDF.filter($"CEO_FIRST_NAME".contains("Shopify") || $"CEO_FIRST_NAME".contains("Square") || $"CEO_FIRST_NAME".contains("BigCommerce") || $"CEO_FIRST_NAME".contains("Wix") || $"CEO_FIRST_NAME".contains("SquareSpace") || $"CEO_FIRST_NAME".contains("Weebly") || $"CEO_FIRST_NAME".contains("WooCommerce") || $"CEO_FIRST_NAME".contains("Creditkarma") || $"CEO_FIRST_NAME".contains("CreditSesame") || $"CEO_FIRST_NAME".contains("Bankrate") || $"CEO_FIRST_NAME".contains("Nerdwallet") || $"CEO_FIRST_NAME".contains("Clearscore") || $"CEO_FIRST_NAME".contains("Noddle") || $"CEO_FIRST_NAME".contains("LendingTree") || $"CEO_FIRST_NAME".contains("Fathom") || $"CEO_FIRST_NAME".contains("Qvinci") || $"CEO_FIRST_NAME".contains("Spotlight") || $"CEO_FIRST_NAME".contains("Liveplan") || $"CEO_FIRST_NAME".contains("Float") || $"CEO_FIRST_NAME".contains("Futrli") || $"CEO_FIRST_NAME".contains("Wagepoint") || $"CEO_FIRST_NAME".contains("Payment Evolution") || $"CEO_FIRST_NAME".contains("Xero") || $"CEO_FIRST_NAME".contains("KeyPay") || $"CEO_FIRST_NAME".contains("Robinhood") || $"CEO_FIRST_NAME".contains("Acorns") || $"CEO_FIRST_NAME".contains("Digit") || $"CEO_FIRST_NAME".contains("Wealthfront") || $"CEO_FIRST_NAME".contains("MoneyLion") || $"CEO_FIRST_NAME".contains("Betterment"))
        val CEO_LAST_NAME = newDF.filter($"CEO_LAST_NAME".contains("Shopify") || $"CEO_LAST_NAME".contains("Square") || $"CEO_LAST_NAME".contains("BigCommerce") || $"CEO_LAST_NAME".contains("Wix") || $"CEO_LAST_NAME".contains("SquareSpace") || $"CEO_LAST_NAME".contains("Weebly") || $"CEO_LAST_NAME".contains("WooCommerce") || $"CEO_LAST_NAME".contains("Creditkarma") || $"CEO_LAST_NAME".contains("CreditSesame") || $"CEO_LAST_NAME".contains("Bankrate") || $"CEO_LAST_NAME".contains("Nerdwallet") || $"CEO_LAST_NAME".contains("Clearscore") || $"CEO_LAST_NAME".contains("Noddle") || $"CEO_LAST_NAME".contains("LendingTree") || $"CEO_LAST_NAME".contains("Fathom") || $"CEO_LAST_NAME".contains("Qvinci") || $"CEO_LAST_NAME".contains("Spotlight") || $"CEO_LAST_NAME".contains("Liveplan") || $"CEO_LAST_NAME".contains("Float") || $"CEO_LAST_NAME".contains("Futrli") || $"CEO_LAST_NAME".contains("Wagepoint") || $"CEO_LAST_NAME".contains("Payment Evolution") || $"CEO_LAST_NAME".contains("Xero") || $"CEO_LAST_NAME".contains("KeyPay") || $"CEO_LAST_NAME".contains("Robinhood") || $"CEO_LAST_NAME".contains("Acorns") || $"CEO_LAST_NAME".contains("Digit") || $"CEO_LAST_NAME".contains("Wealthfront") || $"CEO_LAST_NAME".contains("MoneyLion") || $"CEO_LAST_NAME".contains("Betterment"))
        val TRADESTYLE_1 = newDF.filter($"TRADESTYLE_1".contains("Shopify") || $"TRADESTYLE_1".contains("Square") || $"TRADESTYLE_1".contains("BigCommerce") || $"TRADESTYLE_1".contains("Wix") || $"TRADESTYLE_1".contains("SquareSpace") || $"TRADESTYLE_1".contains("Weebly") || $"TRADESTYLE_1".contains("WooCommerce") || $"TRADESTYLE_1".contains("Creditkarma") || $"TRADESTYLE_1".contains("CreditSesame") || $"TRADESTYLE_1".contains("Bankrate") || $"TRADESTYLE_1".contains("Nerdwallet") || $"TRADESTYLE_1".contains("Clearscore") || $"TRADESTYLE_1".contains("Noddle") || $"TRADESTYLE_1".contains("LendingTree") || $"TRADESTYLE_1".contains("Fathom") || $"TRADESTYLE_1".contains("Qvinci") || $"TRADESTYLE_1".contains("Spotlight") || $"TRADESTYLE_1".contains("Liveplan") || $"TRADESTYLE_1".contains("Float") || $"TRADESTYLE_1".contains("Futrli") || $"TRADESTYLE_1".contains("Wagepoint") || $"TRADESTYLE_1".contains("Payment Evolution") || $"TRADESTYLE_1".contains("Xero") || $"TRADESTYLE_1".contains("KeyPay") || $"TRADESTYLE_1".contains("Robinhood") || $"TRADESTYLE_1".contains("Acorns") || $"TRADESTYLE_1".contains("Digit") || $"TRADESTYLE_1".contains("Wealthfront") || $"TRADESTYLE_1".contains("MoneyLion") || $"TRADESTYLE_1".contains("Betterment"))
        //val MAILING_ADDRESS = newDF.filter($"MAILING_ADDRESS".contains("Shopify") || $"MAILING_ADDRESS".contains("Square") || $"MAILING_ADDRESS".contains("BigCommerce") || $"MAILING_ADDRESS".contains("Wix") || $"MAILING_ADDRESS".contains("SquareSpace") || $"MAILING_ADDRESS".contains("Weebly") || $"MAILING_ADDRESS".contains("WooCommerce") || $"MAILING_ADDRESS".contains("Creditkarma") || $"MAILING_ADDRESS".contains("CreditSesame") || $"MAILING_ADDRESS".contains("Bankrate") || $"MAILING_ADDRESS".contains("Nerdwallet") || $"MAILING_ADDRESS".contains("Clearscore") || $"MAILING_ADDRESS".contains("Noddle") || $"MAILING_ADDRESS".contains("LendingTree") || $"MAILING_ADDRESS".contains("Fathom") || $"MAILING_ADDRESS".contains("Qvinci") || $"MAILING_ADDRESS".contains("Spotlight") || $"MAILING_ADDRESS".contains("Liveplan") || $"MAILING_ADDRESS".contains("Float") || $"MAILING_ADDRESS".contains("Futrli") || $"MAILING_ADDRESS".contains("Wagepoint") || $"MAILING_ADDRESS".contains("Payment Evolution") || $"MAILING_ADDRESS".contains("Xero") || $"MAILING_ADDRESS".contains("KeyPay") || $"MAILING_ADDRESS".contains("Robinhood") || $"MAILING_ADDRESS".contains("Acorns") || $"MAILING_ADDRESS".contains("Digit") || $"MAILING_ADDRESS".contains("Wealthfront") || $"MAILING_ADDRESS".contains("MoneyLion") || $"MAILING_ADDRESS".contains("Betterment"))
        val MAILING_CITY_NAME = newDF.filter($"MAILING_CITY_NAME".contains("Shopify") || $"MAILING_CITY_NAME".contains("Square") || $"MAILING_CITY_NAME".contains("BigCommerce") || $"MAILING_CITY_NAME".contains("Wix") || $"MAILING_CITY_NAME".contains("SquareSpace") || $"MAILING_CITY_NAME".contains("Weebly") || $"MAILING_CITY_NAME".contains("WooCommerce") || $"MAILING_CITY_NAME".contains("Creditkarma") || $"MAILING_CITY_NAME".contains("CreditSesame") || $"MAILING_CITY_NAME".contains("Bankrate") || $"MAILING_CITY_NAME".contains("Nerdwallet") || $"MAILING_CITY_NAME".contains("Clearscore") || $"MAILING_CITY_NAME".contains("Noddle") || $"MAILING_CITY_NAME".contains("LendingTree") || $"MAILING_CITY_NAME".contains("Fathom") || $"MAILING_CITY_NAME".contains("Qvinci") || $"MAILING_CITY_NAME".contains("Spotlight") || $"MAILING_CITY_NAME".contains("Liveplan") || $"MAILING_CITY_NAME".contains("Float") || $"MAILING_CITY_NAME".contains("Futrli") || $"MAILING_CITY_NAME".contains("Wagepoint") || $"MAILING_CITY_NAME".contains("Payment Evolution") || $"MAILING_CITY_NAME".contains("Xero") || $"MAILING_CITY_NAME".contains("KeyPay") || $"MAILING_CITY_NAME".contains("Robinhood") || $"MAILING_CITY_NAME".contains("Acorns") || $"MAILING_CITY_NAME".contains("Digit") || $"MAILING_CITY_NAME".contains("Wealthfront") || $"MAILING_CITY_NAME".contains("MoneyLion") || $"MAILING_CITY_NAME".contains("Betterment"))
        //val DOMAIN_5 = newDF.filter($"DOMAIN_5".contains("Shopify") || $"DOMAIN_5".contains("Square") || $"DOMAIN_5".contains("BigCommerce") || $"DOMAIN_5".contains("Wix") || $"DOMAIN_5".contains("SquareSpace") || $"DOMAIN_5".contains("Weebly") || $"DOMAIN_5".contains("WooCommerce") || $"DOMAIN_5".contains("Creditkarma") || $"DOMAIN_5".contains("CreditSesame") || $"DOMAIN_5".contains("Bankrate") || $"DOMAIN_5".contains("Nerdwallet") || $"DOMAIN_5".contains("Clearscore") || $"DOMAIN_5".contains("Noddle") || $"DOMAIN_5".contains("LendingTree") || $"DOMAIN_5".contains("Fathom") || $"DOMAIN_5".contains("Qvinci") || $"DOMAIN_5".contains("Spotlight") || $"DOMAIN_5".contains("Liveplan") || $"DOMAIN_5".contains("Float") || $"DOMAIN_5".contains("Futrli") || $"DOMAIN_5".contains("Wagepoint") || $"DOMAIN_5".contains("Payment Evolution") || $"DOMAIN_5".contains("Xero") || $"DOMAIN_5".contains("KeyPay") || $"DOMAIN_5".contains("Robinhood") || $"DOMAIN_5".contains("Acorns") || $"DOMAIN_5".contains("Digit") || $"DOMAIN_5".contains("Wealthfront") || $"DOMAIN_5".contains("MoneyLion") || $"DOMAIN_5".contains("Betterment"))
        val HEADQUARTER_PARENT_CITY_NAME = newDF.filter($"HEADQUARTER/PARENT_CITY_NAME".contains("Shopify") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Square") || $"HEADQUARTER/PARENT_CITY_NAME".contains("BigCommerce") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Wix") || $"HEADQUARTER/PARENT_CITY_NAME".contains("SquareSpace") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Weebly") || $"HEADQUARTER/PARENT_CITY_NAME".contains("WooCommerce") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Creditkarma") || $"HEADQUARTER/PARENT_CITY_NAME".contains("CreditSesame") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Bankrate") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Nerdwallet") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Clearscore") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Noddle") || $"HEADQUARTER/PARENT_CITY_NAME".contains("LendingTree") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Fathom") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Qvinci") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Spotlight") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Liveplan") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Float") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Futrli") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Wagepoint") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Payment Evolution") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Xero") || $"HEADQUARTER/PARENT_CITY_NAME".contains("KeyPay") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Robinhood") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Acorns") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Digit") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Wealthfront") || $"HEADQUARTER/PARENT_CITY_NAME".contains("MoneyLion") || $"HEADQUARTER/PARENT_CITY_NAME".contains("Betterment"))
        //val LINE_OF_BUSINESS = newDF.filter($"LINE_OF_BUSINESS".contains("Shopify") || $"LINE_OF_BUSINESS".contains("Square") || $"LINE_OF_BUSINESS".contains("BigCommerce") || $"LINE_OF_BUSINESS".contains("Wix") || $"LINE_OF_BUSINESS".contains("SquareSpace") || $"LINE_OF_BUSINESS".contains("Weebly") || $"LINE_OF_BUSINESS".contains("WooCommerce") || $"LINE_OF_BUSINESS".contains("Creditkarma") || $"LINE_OF_BUSINESS".contains("CreditSesame") || $"LINE_OF_BUSINESS".contains("Bankrate") || $"LINE_OF_BUSINESS".contains("Nerdwallet") || $"LINE_OF_BUSINESS".contains("Clearscore") || $"LINE_OF_BUSINESS".contains("Noddle") || $"LINE_OF_BUSINESS".contains("LendingTree") || $"LINE_OF_BUSINESS".contains("Fathom") || $"LINE_OF_BUSINESS".contains("Qvinci") || $"LINE_OF_BUSINESS".contains("Spotlight") || $"LINE_OF_BUSINESS".contains("Liveplan") || $"LINE_OF_BUSINESS".contains("Float") || $"LINE_OF_BUSINESS".contains("Futrli") || $"LINE_OF_BUSINESS".contains("Wagepoint") || $"LINE_OF_BUSINESS".contains("Payment Evolution") || $"LINE_OF_BUSINESS".contains("Xero") || $"LINE_OF_BUSINESS".contains("KeyPay") || $"LINE_OF_BUSINESS".contains("Robinhood") || $"LINE_OF_BUSINESS".contains("Acorns") || $"LINE_OF_BUSINESS".contains("Digit") || $"LINE_OF_BUSINESS".contains("Wealthfront") || $"LINE_OF_BUSINESS".contains("MoneyLion") || $"LINE_OF_BUSINESS".contains("Betterment"))
        val US_1987_SIC_1_DESCRIPTION = newDF.filter($"US_1987_SIC_1_DESCRIPTION".contains("Shopify") || $"US_1987_SIC_1_DESCRIPTION".contains("Square") || $"US_1987_SIC_1_DESCRIPTION".contains("BigCommerce") || $"US_1987_SIC_1_DESCRIPTION".contains("Wix") || $"US_1987_SIC_1_DESCRIPTION".contains("SquareSpace") || $"US_1987_SIC_1_DESCRIPTION".contains("Weebly") || $"US_1987_SIC_1_DESCRIPTION".contains("WooCommerce") || $"US_1987_SIC_1_DESCRIPTION".contains("Creditkarma") || $"US_1987_SIC_1_DESCRIPTION".contains("CreditSesame") || $"US_1987_SIC_1_DESCRIPTION".contains("Bankrate") || $"US_1987_SIC_1_DESCRIPTION".contains("Nerdwallet") || $"US_1987_SIC_1_DESCRIPTION".contains("Clearscore") || $"US_1987_SIC_1_DESCRIPTION".contains("Noddle") || $"US_1987_SIC_1_DESCRIPTION".contains("LendingTree") || $"US_1987_SIC_1_DESCRIPTION".contains("Fathom") || $"US_1987_SIC_1_DESCRIPTION".contains("Qvinci") || $"US_1987_SIC_1_DESCRIPTION".contains("Spotlight") || $"US_1987_SIC_1_DESCRIPTION".contains("Liveplan") || $"US_1987_SIC_1_DESCRIPTION".contains("Float") || $"US_1987_SIC_1_DESCRIPTION".contains("Futrli") || $"US_1987_SIC_1_DESCRIPTION".contains("Wagepoint") || $"US_1987_SIC_1_DESCRIPTION".contains("Payment Evolution") || $"US_1987_SIC_1_DESCRIPTION".contains("Xero") || $"US_1987_SIC_1_DESCRIPTION".contains("KeyPay") || $"US_1987_SIC_1_DESCRIPTION".contains("Robinhood") || $"US_1987_SIC_1_DESCRIPTION".contains("Acorns") || $"US_1987_SIC_1_DESCRIPTION".contains("Digit") || $"US_1987_SIC_1_DESCRIPTION".contains("Wealthfront") || $"US_1987_SIC_1_DESCRIPTION".contains("MoneyLion") || $"US_1987_SIC_1_DESCRIPTION".contains("Betterment"))
        val US_1987_SIC_2_DESCRIPTION = newDF.filter($"US_1987_SIC_2_DESCRIPTION".contains("Shopify") || $"US_1987_SIC_2_DESCRIPTION".contains("Square") || $"US_1987_SIC_2_DESCRIPTION".contains("BigCommerce") || $"US_1987_SIC_2_DESCRIPTION".contains("Wix") || $"US_1987_SIC_2_DESCRIPTION".contains("SquareSpace") || $"US_1987_SIC_2_DESCRIPTION".contains("Weebly") || $"US_1987_SIC_2_DESCRIPTION".contains("WooCommerce") || $"US_1987_SIC_2_DESCRIPTION".contains("Creditkarma") || $"US_1987_SIC_2_DESCRIPTION".contains("CreditSesame") || $"US_1987_SIC_2_DESCRIPTION".contains("Bankrate") || $"US_1987_SIC_2_DESCRIPTION".contains("Nerdwallet") || $"US_1987_SIC_2_DESCRIPTION".contains("Clearscore") || $"US_1987_SIC_2_DESCRIPTION".contains("Noddle") || $"US_1987_SIC_2_DESCRIPTION".contains("LendingTree") || $"US_1987_SIC_2_DESCRIPTION".contains("Fathom") || $"US_1987_SIC_2_DESCRIPTION".contains("Qvinci") || $"US_1987_SIC_2_DESCRIPTION".contains("Spotlight") || $"US_1987_SIC_2_DESCRIPTION".contains("Liveplan") || $"US_1987_SIC_2_DESCRIPTION".contains("Float") || $"US_1987_SIC_2_DESCRIPTION".contains("Futrli") || $"US_1987_SIC_2_DESCRIPTION".contains("Wagepoint") || $"US_1987_SIC_2_DESCRIPTION".contains("Payment Evolution") || $"US_1987_SIC_2_DESCRIPTION".contains("Xero") || $"US_1987_SIC_2_DESCRIPTION".contains("KeyPay") || $"US_1987_SIC_2_DESCRIPTION".contains("Robinhood") || $"US_1987_SIC_2_DESCRIPTION".contains("Acorns") || $"US_1987_SIC_2_DESCRIPTION".contains("Digit") || $"US_1987_SIC_2_DESCRIPTION".contains("Wealthfront") || $"US_1987_SIC_2_DESCRIPTION".contains("MoneyLion") || $"US_1987_SIC_2_DESCRIPTION".contains("Betterment"))
        //val STATE_NAME = newDF.filter($"STATE_NAME".contains("Shopify") || $"STATE_NAME".contains("Square") || $"STATE_NAME".contains("BigCommerce") || $"STATE_NAME".contains("Wix") || $"STATE_NAME".contains("SquareSpace") || $"STATE_NAME".contains("Weebly") || $"STATE_NAME".contains("WooCommerce") || $"STATE_NAME".contains("Creditkarma") || $"STATE_NAME".contains("CreditSesame") || $"STATE_NAME".contains("Bankrate") || $"STATE_NAME".contains("Nerdwallet") || $"STATE_NAME".contains("Clearscore") || $"STATE_NAME".contains("Noddle") || $"STATE_NAME".contains("LendingTree") || $"STATE_NAME".contains("Fathom") || $"STATE_NAME".contains("Qvinci") || $"STATE_NAME".contains("Spotlight") || $"STATE_NAME".contains("Liveplan") || $"STATE_NAME".contains("Float") || $"STATE_NAME".contains("Futrli") || $"STATE_NAME".contains("Wagepoint") || $"STATE_NAME".contains("Payment Evolution") || $"STATE_NAME".contains("Xero") || $"STATE_NAME".contains("KeyPay") || $"STATE_NAME".contains("Robinhood") || $"STATE_NAME".contains("Acorns") || $"STATE_NAME".contains("Digit") || $"STATE_NAME".contains("Wealthfront") || $"STATE_NAME".contains("MoneyLion") || $"STATE_NAME".contains("Betterment"))
        //val SMSA_NAME = newDF.filter($"SMSA_NAME".contains("Shopify") || $"SMSA_NAME".contains("Square") || $"SMSA_NAME".contains("BigCommerce") || $"SMSA_NAME".contains("Wix") || $"SMSA_NAME".contains("SquareSpace") || $"SMSA_NAME".contains("Weebly") || $"SMSA_NAME".contains("WooCommerce") || $"SMSA_NAME".contains("Creditkarma") || $"SMSA_NAME".contains("CreditSesame") || $"SMSA_NAME".contains("Bankrate") || $"SMSA_NAME".contains("Nerdwallet") || $"SMSA_NAME".contains("Clearscore") || $"SMSA_NAME".contains("Noddle") || $"SMSA_NAME".contains("LendingTree") || $"SMSA_NAME".contains("Fathom") || $"SMSA_NAME".contains("Qvinci") || $"SMSA_NAME".contains("Spotlight") || $"SMSA_NAME".contains("Liveplan") || $"SMSA_NAME".contains("Float") || $"SMSA_NAME".contains("Futrli") || $"SMSA_NAME".contains("Wagepoint") || $"SMSA_NAME".contains("Payment Evolution") || $"SMSA_NAME".contains("Xero") || $"SMSA_NAME".contains("KeyPay") || $"SMSA_NAME".contains("Robinhood") || $"SMSA_NAME".contains("Acorns") || $"SMSA_NAME".contains("Digit") || $"SMSA_NAME".contains("Wealthfront") || $"SMSA_NAME".contains("MoneyLion") || $"SMSA_NAME".contains("Betterment"))
        val ACCOUNTING_FIRM_NAME = newDF.filter($"ACCOUNTING_FIRM_NAME".contains("Shopify") || $"ACCOUNTING_FIRM_NAME".contains("Square") || $"ACCOUNTING_FIRM_NAME".contains("BigCommerce") || $"ACCOUNTING_FIRM_NAME".contains("Wix") || $"ACCOUNTING_FIRM_NAME".contains("SquareSpace") || $"ACCOUNTING_FIRM_NAME".contains("Weebly") || $"ACCOUNTING_FIRM_NAME".contains("WooCommerce") || $"ACCOUNTING_FIRM_NAME".contains("Creditkarma") || $"ACCOUNTING_FIRM_NAME".contains("CreditSesame") || $"ACCOUNTING_FIRM_NAME".contains("Bankrate") || $"ACCOUNTING_FIRM_NAME".contains("Nerdwallet") || $"ACCOUNTING_FIRM_NAME".contains("Clearscore") || $"ACCOUNTING_FIRM_NAME".contains("Noddle") || $"ACCOUNTING_FIRM_NAME".contains("LendingTree") || $"ACCOUNTING_FIRM_NAME".contains("Fathom") || $"ACCOUNTING_FIRM_NAME".contains("Qvinci") || $"ACCOUNTING_FIRM_NAME".contains("Spotlight") || $"ACCOUNTING_FIRM_NAME".contains("Liveplan") || $"ACCOUNTING_FIRM_NAME".contains("Float") || $"ACCOUNTING_FIRM_NAME".contains("Futrli") || $"ACCOUNTING_FIRM_NAME".contains("Wagepoint") || $"ACCOUNTING_FIRM_NAME".contains("Payment Evolution") || $"ACCOUNTING_FIRM_NAME".contains("Xero") || $"ACCOUNTING_FIRM_NAME".contains("KeyPay") || $"ACCOUNTING_FIRM_NAME".contains("Robinhood") || $"ACCOUNTING_FIRM_NAME".contains("Acorns") || $"ACCOUNTING_FIRM_NAME".contains("Digit") || $"ACCOUNTING_FIRM_NAME".contains("Wealthfront") || $"ACCOUNTING_FIRM_NAME".contains("MoneyLion") || $"ACCOUNTING_FIRM_NAME".contains("Betterment"))
        //val FIRST_EXECUTIVE_FIRST_NAME = newDF.filter($"FIRST_EXECUTIVE_FIRST_NAME".contains("Shopify") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Square") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("BigCommerce") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Wix") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("SquareSpace") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Weebly") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("WooCommerce") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Creditkarma") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("CreditSesame") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Bankrate") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Nerdwallet") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Clearscore") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Noddle") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("LendingTree") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Fathom") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Qvinci") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Spotlight") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Liveplan") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Float") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Futrli") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Wagepoint") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Payment Evolution") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Xero") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("KeyPay") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Robinhood") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Acorns") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Digit") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Wealthfront") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("MoneyLion") || $"FIRST_EXECUTIVE_FIRST_NAME".contains("Betterment"))
        val FIRST_EXECUTIVE_LAST_NAME = newDF.filter($"FIRST_EXECUTIVE_LAST_NAME".contains("Shopify") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Square") || $"FIRST_EXECUTIVE_LAST_NAME".contains("BigCommerce") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Wix") || $"FIRST_EXECUTIVE_LAST_NAME".contains("SquareSpace") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Weebly") || $"FIRST_EXECUTIVE_LAST_NAME".contains("WooCommerce") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Creditkarma") || $"FIRST_EXECUTIVE_LAST_NAME".contains("CreditSesame") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Bankrate") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Nerdwallet") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Clearscore") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Noddle") || $"FIRST_EXECUTIVE_LAST_NAME".contains("LendingTree") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Fathom") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Qvinci") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Spotlight") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Liveplan") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Float") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Futrli") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Wagepoint") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Payment Evolution") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Xero") || $"FIRST_EXECUTIVE_LAST_NAME".contains("KeyPay") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Robinhood") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Acorns") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Digit") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Wealthfront") || $"FIRST_EXECUTIVE_LAST_NAME".contains("MoneyLion") || $"FIRST_EXECUTIVE_LAST_NAME".contains("Betterment"))
        //val SECOND_EXECUTIVE_FIRST_NAME = newDF.filter($"SECOND_EXECUTIVE_FIRST_NAME".contains("Shopify") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Square") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("BigCommerce") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Wix") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("SquareSpace") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Weebly") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("WooCommerce") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Creditkarma") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("CreditSesame") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Bankrate") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Nerdwallet") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Clearscore") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Noddle") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("LendingTree") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Fathom") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Qvinci") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Spotlight") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Liveplan") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Float") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Futrli") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Wagepoint") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Payment Evolution") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Xero") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("KeyPay") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Robinhood") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Acorns") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Digit") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Wealthfront") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("MoneyLion") || $"SECOND_EXECUTIVE_FIRST_NAME".contains("Betterment"))
        val SECOND_EXECUTIVE_LAST_NAME = newDF.filter($"SECOND_EXECUTIVE_LAST_NAME".contains("Shopify") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Square") || $"SECOND_EXECUTIVE_LAST_NAME".contains("BigCommerce") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Wix") || $"SECOND_EXECUTIVE_LAST_NAME".contains("SquareSpace") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Weebly") || $"SECOND_EXECUTIVE_LAST_NAME".contains("WooCommerce") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Creditkarma") || $"SECOND_EXECUTIVE_LAST_NAME".contains("CreditSesame") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Bankrate") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Nerdwallet") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Clearscore") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Noddle") || $"SECOND_EXECUTIVE_LAST_NAME".contains("LendingTree") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Fathom") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Qvinci") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Spotlight") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Liveplan") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Float") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Futrli") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Wagepoint") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Payment Evolution") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Xero") || $"SECOND_EXECUTIVE_LAST_NAME".contains("KeyPay") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Robinhood") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Acorns") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Digit") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Wealthfront") || $"SECOND_EXECUTIVE_LAST_NAME".contains("MoneyLion") || $"SECOND_EXECUTIVE_LAST_NAME".contains("Betterment"))
        //val THIRD_EXECUTIVE_FIRST_NAME = newDF.filter($"THIRD_EXECUTIVE_FIRST_NAME".contains("Shopify") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Square") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("BigCommerce") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Wix") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("SquareSpace") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Weebly") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("WooCommerce") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Creditkarma") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("CreditSesame") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Bankrate") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Nerdwallet") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Clearscore") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Noddle") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("LendingTree") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Fathom") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Qvinci") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Spotlight") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Liveplan") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Float") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Futrli") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Wagepoint") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Payment Evolution") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Xero") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("KeyPay") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Robinhood") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Acorns") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Digit") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Wealthfront") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("MoneyLion") || $"THIRD_EXECUTIVE_FIRST_NAME".contains("Betterment"))
        val THIRD_EXECUTIVE_LAST_NAME = newDF.filter($"THIRD_EXECUTIVE_LAST_NAME".contains("Shopify") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Square") || $"THIRD_EXECUTIVE_LAST_NAME".contains("BigCommerce") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Wix") || $"THIRD_EXECUTIVE_LAST_NAME".contains("SquareSpace") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Weebly") || $"THIRD_EXECUTIVE_LAST_NAME".contains("WooCommerce") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Creditkarma") || $"THIRD_EXECUTIVE_LAST_NAME".contains("CreditSesame") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Bankrate") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Nerdwallet") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Clearscore") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Noddle") || $"THIRD_EXECUTIVE_LAST_NAME".contains("LendingTree") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Fathom") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Qvinci") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Spotlight") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Liveplan") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Float") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Futrli") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Wagepoint") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Payment Evolution") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Xero") || $"THIRD_EXECUTIVE_LAST_NAME".contains("KeyPay") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Robinhood") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Acorns") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Digit") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Wealthfront") || $"THIRD_EXECUTIVE_LAST_NAME".contains("MoneyLion") || $"THIRD_EXECUTIVE_LAST_NAME".contains("Betterment"))


        val final_outputDF = BUSINESS_NAME
                             .union(STREET_ADDRESS)
                             .union(CITY_NAME)
                             .union(GLOBAL_ULTIMATE_BUSINESS_NAME)
                             .union(HEADQUARTER_PARENT_BUSINESS_NAME)
                             .union(CEO_NAME)
                             .union(CEO_FIRST_NAME)
                             .union(CEO_LAST_NAME)
                             .union(TRADESTYLE_1)
                             .union(MAILING_CITY_NAME)
                             .union(HEADQUARTER_PARENT_CITY_NAME)
                             .union(US_1987_SIC_1_DESCRIPTION)
                             .union(US_1987_SIC_2_DESCRIPTION)
                             .union(ACCOUNTING_FIRM_NAME)
                             .union(FIRST_EXECUTIVE_LAST_NAME)
                             .union(SECOND_EXECUTIVE_LAST_NAME)
                             .union(THIRD_EXECUTIVE_LAST_NAME)


        val FINALDATA_OUTPUT = final_outputDF.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/FINALDATA")

    */




/*
    // val COUNTY_NAMEDF = COUNTY_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/COUNTY_NAME")
    val BUSINESS_NAMEDF = BUSINESS_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/BUSINESS_NAME")
    val STREET_ADDRESSDF = STREET_ADDRESS.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/STREET_ADDRESS")
    //val STREET_ADDRESS2DF = STREET_ADDRESS2.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/STREET_ADDRESS2")
    val CITY_NAMEDF = CITY_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/CITY_NAME")
    val GLOBAL_ULTIMATE_BUSINESS_NAMEDF = GLOBAL_ULTIMATE_BUSINESS_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/GLOBAL_ULTIMATE_BUSINESS_NAME")
    val HEADQUARTER_PARENT_BUSINESS_NAMEDF = HEADQUARTER_PARENT_BUSINESS_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/HEADQUARTER_PARENT_BUSINESS_NAME")
    val CEO_NAMEDF = CEO_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/CEO_NAME")
    val CEO_FIRST_NAMEDF = CEO_FIRST_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/CEO_FIRST_NAME")
    val CEO_LAST_NAMEDF = CEO_LAST_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/CEO_LAST_NAME")
    val TRADESTYLE_1DF = TRADESTYLE_1.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/TRADESTYLE_1")
    //val MAILING_ADDRESSDF = MAILING_ADDRESS.write.json("/Users/pswain1/workspace/JsonFormatOutput/MAILING_ADDRESS")
    val MAILING_CITY_NAMEDF = MAILING_CITY_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/MAILING_CITY_NAME")
    // val DOMAIN_5DF = DOMAIN_5.write.json("/Users/pswain1/workspace/JsonFormatOutput/DOMAIN_5")
    val HEADQUARTER_PARENT_CITY_NAMEDF = HEADQUARTER_PARENT_CITY_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/HEADQUARTER_PARENT_CITY_NAME")
    //val LINE_OF_BUSINESSDF = LINE_OF_BUSINESS.write.json("/Users/pswain1/workspace/JsonFormatOutput/LINE_OF_BUSINESS")
    val US_1987_SIC_1_DESCRIPTIONDF = US_1987_SIC_1_DESCRIPTION.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/US_1987_SIC_1_DESCRIPTION")
    val US_1987_SIC_2_DESCRIPTIONDF = US_1987_SIC_2_DESCRIPTION.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/US_1987_SIC_2_DESCRIPTION")
    //val STATE_NAMEDF = STATE_NAME.write.json("/Users/pswain1/workspace/JsonFormatOutput/STATE_NAME")
    //val SMSA_NAMEDF = SMSA_NAME.write.json("/Users/pswain1/workspace/JsonFormatOutput/SMSA_NAME")
    val ACCOUNTING_FIRM_NAMEDF = ACCOUNTING_FIRM_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/ACCOUNTING_FIRM_NAME")
    //val FIRST_EXECUTIVE_FIRST_NAMEDF = FIRST_EXECUTIVE_FIRST_NAME.write.json("/Users/pswain1/workspace/JsonFormatOutput/FIRST_EXECUTIVE_FIRST_NAME")
    val FIRST_EXECUTIVE_LAST_NAMEDF = FIRST_EXECUTIVE_LAST_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/FIRST_EXECUTIVE_LAST_NAME")
    //val SECOND_EXECUTIVE_FIRST_NAMEDF = SECOND_EXECUTIVE_FIRST_NAME.write.json("/Users/pswain1/workspace/JsonFormatOutput/SECOND_EXECUTIVE_FIRST_NAME")
    val SECOND_EXECUTIVE_LAST_NAMEDF = SECOND_EXECUTIVE_LAST_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/SECOND_EXECUTIVE_LAST_NAME")
    //val THIRD_EXECUTIVE_FIRST_NAMEDF = THIRD_EXECUTIVE_FIRST_NAME.write.json("/Users/pswain1/workspace/JsonFormatOutput/THIRD_EXECUTIVE_FIRST_NAME")
    val THIRD_EXECUTIVE_LAST_NAMEDF = THIRD_EXECUTIVE_LAST_NAME.coalesce(1).write.json("/Users/pswain1/workspace/JsonFormatOutput/THIRD_EXECUTIVE_LAST_NAME")


    // val jsonDF1 = filterDF.write.json("/Users/pswain1/workspace/JsonFormatOutput/output1")

*/

  }
}


// ('Shopify','Square','BigCommerce','Wix','SquareSpace','Weebly','WooCommerce','Creditkarma','CreditSesame','Bankrate','Nerdwallet','Clearscore','Noddle','LendingTree','Fathom','Qvinci','Spotlight','Liveplan','Float','Futrli','Wagepoint','Payment Evolution','Xero','KeyPay','Robinhood','Acorns','Digit','Wealthfront','MoneyLion','Betterment')

// $"COUNTY_NAME".contains("San Diego")
